version: 2.1
orbs:
  ruby: circleci/ruby@1.0.4
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake spec
  deploy:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Build gem
          command: gem build capim_tictactoe.gemspec
      - run:
          name: Install locally
          command: gem install --development *.gem
      -run:
          name: Publish gem
          command: |
            mkdir -p ~/.gem
            echo -e "---\r\n:rubygems_api_key: $RUBY_GEM_API_KEY" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
            gem push capim_tictactoe*.gem
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
