name: Publish Gem

on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake spec
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v3
      - name: set up secret file
        env:
         GEM_HOST_API_KEY: "${{secrets.GEM_HOST_API_KEY}}"
        run: |
         echo -e "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > sec.txt
         cat sec.txt
      - name: publish gem
        run: |
         mkdir -p $HOME/.gem
         touch $HOME/.gem/credentials
         chmod 0600 $HOME/.gem/credentials
         echo -e "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
         gem build *.gemspec
         gem push *.gem

        
